name: "Azure Infrastructure setup using Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest  # Linux-based runner

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Azure using the AZURE_CREDENTIALS secret (JSON format)
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        working-directory: scripts/terraform
        run: terraform init

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        working-directory: scripts/terraform
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        working-directory: scripts/terraform
        run: terraform apply -auto-approve
