name: "Azure Infrastructure setup using Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Azure using the AZURE_CREDENTIALS secret (JSON format)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Extract Azure credentials from the GitHub Secret
      - name: Extract Azure Credentials
        id: extract_creds
        run: |
          echo "clientId=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)" >> $GITHUB_ENV
          echo "clientSecret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" >> $GITHUB_ENV
          echo "subscriptionId=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" >> $GITHUB_ENV
          echo "tenantId=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)" >> $GITHUB_ENV

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        working-directory: scripts/terraform
        run: terraform init

      # Plan Terraform deployment
      - name: Terraform Plan
        working-directory: scripts/terraform
        run: terraform plan -var "client_id=$clientId" -var "client_secret=$clientSecret" -var "subscription_id=$subscriptionId" -var "tenant_id=$tenantId"


      # Apply Terraform Configuration
      - name: Terraform Apply
        working-directory: scripts/terraform
        run: |
          terraform apply -auto-approve \
            -var "client_id=$clientId" \
            -var "client_secret=$clientSecret" \
            -var "subscription_id=$subscriptionId" \
            -var "tenant_id=$tenantId"

